# Generated by Django 6.1 on 2026-09-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_menuitem_user_role_alter_user_email_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('WAITER', 'Waiter'), ('CHEF', 'Chef'), ('MANAGER', 'Manager')], default='CUSTOMER', max_length=20),
        ),
    ]
