# Generated by Django 6.1 on 2026-09-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='allergen_tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
