# Generated by Django 6.1 on 2026-09-26 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_tablecheckin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresignedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presigned_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
