# Generated by Django 6.1 on 2026-09-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_presignedupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
